Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "tcp_serv.py", line 23, in handle_client
    client_socket.send("ACK!")
TypeError: a bytes-like object is required, not 'str'
